### ISSUE TITLE
Use leveldb / levelgraph / levelgraph-n3 / levelgraph-jsonld

### ISSUE THREAD

**Issue by transcranial** [standard-analytics/mesh-tree#3]
Will allow for increased functionality by incorporating the complete MeSH descriptor records. Will leave out qualifier and supplementary concept records for now.

**Comment by sballesteros** [comment]
+1
Also, have you seen https://github.com/HHS/meshrdf ?

**Comment by transcranial** [comment]
Will definitely look into it. My goal for restructuring MeSH into leveldb is to have a fast, persistent datastore to help support classification tasks. Using [levelgraph](https://github.com/mcollina/levelgraph) and [levelgraph-jsonld](https://github.com/mcollina/levelgraph-jsonld), we can better incorporate concept qualifiers, which will be huge - and possibly essential - for context disambiguation.

**Comment by transcranial** [comment]
Using levelgraph-n3 and levelgraph-jsonld. MeSH as RDF n-triple file is ~1.8 GB. Note memory issue with levelgraph-n3 https://github.com/mcollina/levelgraph/issues/84. Will look into this further.

Will also look into [linked data fragments](http://linkeddatafragments.org/).

**Comment by transcranial** [comment]
No issues with levelgraph-n3 data import. Merged branch `3-leveldb` into `master`
